language: python
install:
- pip install -r requirements.txt
script:
- mkdocs build --config-file=docs/mkdocs.yml --verbose --clean
- mv docs/site .
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
      branch: master