site_name: Solstice - Pipeline Docs
dev_addr: '127.0.0.1:9000'
sticky_navigation: False
nav:
    - Home: index.md
    - First Steps:
      - 'NDA': 'nda.md'
      - 'Shading Test': 'shadingtest.md'
    - Artella App:
        - What's Artella App?: pipeline/artella/app.md
        - Installing Artella App: pipeline/artella/installing.md
        - Managing the Artella App: pipeline/artella/managing.md
    - Solstice Launcher:
        - What's Solstice Launcher?: pipeline/launcher/app.md
        - Installing Solstice Launcher: pipeline/launcher/installation.md
        - Using Solstice Launcher: pipeline/launcher/usage.md
        - Uninstalling Solstice Launcher: pipeline/launcher/uninstall.md
    - Solstice Pipeline:
        - Software:
            - Versions: pipeline/software/versions.md
            - Installation:
                - Maya: pipeline/software/installingmaya.md
                - Arnold: pipeline/software/installingarnold.md
                - Yeti: pipeline/software/installingyeti.md
        - Tools:
            - Welcome: pipeline/tools/welcome.md
            - Tray: pipeline/tools/tray.md
            - Shelf: pipeline/tools/shelf.md
            - Changelog: pipeline/tools/changelog.md
            - Assets Manager: pipeline/tools/assetsmanager.md
            - Artella Manager: pipeline/tools/artellamanager.md
            - Artella Uploader: pipeline/tools/artellauploader.md
            - Pickers: pipeline/tools/pickers.md
            -  Alembic Manager: pipeline/tools/alembicmanager.md
            - Light Rigs Manager: pipeline/tools/lightrigmanager.md
theme:
  name: 'material'
  logo: 'img/solstice_avatar.png'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist
plugins:
  - markdownextradata: {}
extra:
  project:
    name: "Solstice"
    exe: "solstice_launcher.exe"
extra_css:
  - 'stylesheets/solstice.css'
